openapi: 3.0.3
tags:
  - name: example
  - name: examples
info:
  contact:
    name: Example
  title: Response example support
  description: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#mediaTypeObject
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/example':
    get:
      summary: Get example
      operationId: get-example
      tags:
        - example
      description: Showcase of responses with an `example` property present.
      responses:
        '200':
          description: OK
          headers:
            TestHeader:
              example: test-example-header
              description: A test example header
              schema:
                type: string
          content:
            application/json:
              example:
                id: 12345
                email: test@example.com
                name: Test user name
        '204':
          description: OK
          content:
            application/json:
              example:
                - id: 12345
                  email: test@example.com
                  name: Test user name
  '/examples':
    get:
      operationId: get-examples
      summary: Get examples
      tags:
        - examples
      description: Showcase of responses with an `examples` property present.
      responses:
        '201':
          description: OK
          content:
            application/json:
              examples:
                user:
                  value:
                    user:
                      email: test@example.com
                      name: Test user name
        '202':
          description: OK
          content:
            application/json:
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    name: Fluffy
                    petType: Cat
                    color: White
                    gender: male
                    breed: Persian
                dog:
                  summary: An example of a dog with a cat's name
                  value:
                    name: Puma
                    petType: Dog
                    color: Black
                    gender: Female
                    breed: Mixed
        '400':
          '$ref': '#/components/responses/400-Response-Ref'
        default:
          description: OK
          content:
            application/json:
              examples:
                response:
                  value:
                    '$ref': '#/components/schemas/UserResponse'
            text/csv, text/comma-separated-values:
              examples:
                display_view=app:
                  value: app1,app2,app3,app4,app5
components:
  schemas:
    UserResponse:
      description: Custom user response example
      example:
        user:
          email: test@example.com
          name: Test user name
  responses:
    400-Response-Ref:
      description: Validation failed
      content:
        application/xml:
          examples:
            response:
              value:
                <?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't
                forget me this weekend!</body></note>
